# Generated by Django 5.1.3 on 2024-11-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('install', 'Install'), ('repair', 'Repair'), ('maintenance', 'Maintenance')], max_length=20)),
                ('request_type', models.CharField(choices=[('new_connection', 'New Connection'), ('maintenance', 'Maintenance'), ('emergency', 'Emergency')], default='maintenance', max_length=20)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
